blog_photo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from .views import created_photo_view, list_post_view, edit_post_view, delete_post_view

app_name = 'gallery'
urlpatterns = [
    path('created_photo/', created_photo_view, name="created_photo"),
    path('list_posts/', list_post_view, name="list_posts"),
    path('list_posts/updated_photo/<int:post_id>', edit_post_view, name="updated_photo"),
    path('list_posts/deleted_photo/<int:post_id>', delete_post_view, name="deleted_photo")
]

gallery/models.py
from django.db import models

# Create your models here.
class Photo(models.Model):
    title = models.CharField(max_length=50, null=False)
    description = models.TextField()
    image = models.ImageField(upload_to='photos/', height_field=None, width_field=None, max_length=None)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

gallery/forms.py
# gallery/forms.py
from django import forms
from .models import Photo

class PhotoForms(forms.ModelForm):
    title = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',  # Classe Bootstrap pour les champs de texte
            'placeholder': 'Entrez le titre de la photo',
            # 'style': 'max-width: 500px;'
        })
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={
            "class": "form-control",  # Classe Bootstrap pour le champ de texte
            "rows": 5,
            "placeholder": "Description détaillée de la photo",
            # 'style': 'max-width: 500px;'
        })
    )
    image = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={
            'class': 'form-control',  # Classe Bootstrap pour les fichiers
            'accept': 'image/*',
            # 'style': 'max-width: 500px;'
        })
    )

    class Meta:
        model = Photo
        fields = ['title', 'description', 'image']

#Validation du formulaire
    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image and image.size > 500 * 1024: #500 ko
            raise forms.ValidationError("La taille de l'image est trop grande, réduisez-là.")
        return image

gallery/views.py
# gallery/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Photo
from .forms import PhotoForms
from django.contrib import messages
from django.utils.translation import gettext as _
from django.core.paginator import Paginator


def created_photo_view(request):
    form = PhotoForms()

    # Vérifie si la requête est un POST avant de valider le formulaire
    if request.method == 'POST':
        form = PhotoForms(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, _("Création réussie !"))
            form = PhotoForms()  # Réinitialise le formulaire après l’enregistrement
        else:
            messages.error(request, _("Échec de création"))

    context = {
        'form': form,
    }
    return render(request, 'gallery/created_photo.html', context=context)


def list_post_view(request):
    query = request.GET.get('search', '')
    posts = Photo.objects.filter(title__icontains=query) if query else Photo.objects.all()

    paginator = Paginator(posts, 2)  #Ici Django divise les photos en plusieurs pages, chaque page contenant 3 posts

    page_number = request.GET.get('page')  #Récupération du numero de page à partir de la requete GET
    page_obj = paginator.get_page(page_number)  #OBTENTION DES POSTS de la page spécifique. C'est l'objet page_obj qui contient le attributs has_next, has_previous et paginator_range

    context = {
        'posts': page_obj,
        'query': query
    }
    return render(request, 'gallery/list_posts.html', context)


def edit_post_view(request, post_id):
    photo = get_object_or_404(Photo, id=post_id)
    form = PhotoForms(request.POST or None, request.FILES or None, instance=photo)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Modifications reussies!")
            return redirect('gallery:list_posts')
        else:
            messages.error(request, "Échec de la mise à jour. Veuillez vérifier les informations fournies.")

    context = {
        'form': form,
        'photo': photo,
    }
    return render(request, 'gallery/update_photo.html', context)


def delete_post_view(request, post_id):
    post = get_object_or_404(Photo, id=post_id)

    post.delete()
    messages.success(request, "post supprimé avec succès !")
    return redirect('gallery:list_posts')  #dans redirect, tu mets le name de la page qui est dans l'url

gallery/templates/gallery/created_photo.html
{% extends "base.html" %}
{% block title %}Création de Photo{% endblock title %}

{% block content %}
    <div class="container mt-5">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        <div class="card shadow-sm p-4 mb-4 bg-white">
            <br>
            <h2 class="mb-4">Création de Post</h2>
            <form method="POST" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <div class=" d-flex justify-content-center mt-4">
                    <button type="submit" class="btn btn-success">Create</button>
                    <a href="{% url 'gallery:created_photo' %}" class="btn btn-secondary ms-2">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

gallery/templates/gallery/list_posts.html
{% extends "base.html" %}
{% load static %}                  
{% block title %}Listing de Posts{% endblock title %}  

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/custom_forms.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
{% endblock extra_css %}

{% block content %}
    <div class="container">
        <br>
        <h2 class="mb-4 text-center">Listing de Posts</h2>
        <form method="GET" action="{% url 'gallery:list_posts' %}" class="form-inline mb-4 d-flex">
            <input type="text" name="search" value="{{ query }}" class="form-control mr-sm-2" placeholder="Rechercher par titre">
            <button type="submit" class="btn btn-primary">Rechercher</button>
        </form>
        {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        {% endif %}

        <div class="row">
            {% for post in posts %}
                <div class="col-md-4 mb-4">
                    <div class="card shadow-sm">
                        <div class="card-img-top" style="height: 200px; overflow: hidden;">
                            <img src="{{ post.image.url }}" alt="Image du post" class="w-100 h-100" style="object-fit: cover;">
                        </div>
                        <div class="card-body d-flex justify-content-between">
                            <h5 class="card-title text-left">{{ post.title }}</h5>
                            <div class="">
                                <a data-toggle="modal" data-target="#modal{{ post.id }}" class="btn btn-link icon-buttons p-0 mr-2">
                                    <i class="bi bi-eye icon-view"></i>
                                </a>
                                <a href="{% url "gallery:updated_photo" post.id %}" class="btn btn-link icon-buttons p-0 mr-2">
                                    <i class="bi bi-pencil icon-edit"></i>
                                </a>
                                <a data-toggle="modal" data-target="#modalSup{{ post.id }}" class="btn btn-link icon-buttons p-0">
                                    <i class="bi bi-trash icon-delete"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modale pour la description -->
                <div class="modal fade" id="modal{{ post.id }}" tabindex="-1" aria-labelledby="modalLabel{{ post.id }}" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modalLabel{{ post.id }}">{{ post.title }}</h5>
                                <button type="button" class="btn btn-close" data-dismiss="modal" aria-label="Close">
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>{{ post.description }}</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>

                {% comment %} Modale pour la suppression {% endcomment %}
                <div class="modal fade" id="modalSup{{ post.id }}" tabindex="-1" aria-labelledby="modalLabel{{ post.id }}" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modalLabel{{ post.id }}">{{ post.title }}</h5>
                            </div>
                            <div class="modal-body">
                                <p>Voulez-vous vraiment supprimer ce post??</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <a type="button" href="{% url "gallery:deleted_photo" post.id %}" class="btn btn-danger">
                                    Delete
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Pagination controls -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if posts.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.previous_page_number }}">Précédent</a>
                    </li>
                {% endif %}
                {% for num in posts.paginator.page_range %}
                    <li class="page-item {% if posts.number == num %}active{% endif %}">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endfor %}
                {% if posts.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.next_page_number }}">Suivant</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock content %}

{% block extra_js %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock extra_js %}

gallery/templates/gallery/update_photo.html
{% extends "base.html" %}
{% block title %}update de Photo{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="card shadow p-4">
        <br>
        <h2 class="mb-4">Mise à jour du post photo</h2>
        <form method="POST" enctype="multipart/form-data" class="p-4 border bg-light">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-right">
                <a href="{% url 'gallery:list_posts' %}" class="btn btn-secondary">Annuler</a>
                <button type="submit" class="btn btn-primary">Mettre à jour</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mon Application{% endblock title %}</title>
    {% block extra_css %}
    {% endblock extra_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

</head>
<body>
    {% block content %}{% endblock content %}

    {% block extra_js %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    {% endblock extra_js %}

</body>
</html>